CREATE TABLE IF NOT EXISTS `userreglist` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(128) NOT NULL,
  `username` varchar(64) DEFAULT NULL,
  `md5pwd` varchar(32) NOT NULL,
  `telephone` varchar(16) DEFAULT NULL,
  `realname` varchar(64) DEFAULT NULL,
  `sex` int(1) NOT NULL DEFAULT '1',
  `university` varchar(128) NOT NULL,
  `college` varchar(64) DEFAULT NULL,
  `category` varchar(16) DEFAULT NULL,
  `graduate` varchar(16) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `constellation` varchar(16) DEFAULT NULL,
  `admyear` int(11) NOT NULL DEFAULT '0',
  `province` varchar(16) DEFAULT NULL,
  `city` varchar(32) DEFAULT NULL,
  `blood` varchar(8) DEFAULT NULL,
  `height` varchar(32) DEFAULT NULL,
  `verify` int(1) NOT NULL DEFAULT '0',
  `matchstate` int(11) DEFAULT '0',
  `locked` int(1) NOT NULL DEFAULT '0',
  `edumail` varchar(128) DEFAULT NULL,
  `edumailcheck` int(1) NOT NULL DEFAULT '0',
  `dream` varchar(1024) DEFAULT NULL,
  `eval` varchar(1024) DEFAULT NULL,
  `hate` varchar(1024) DEFAULT NULL,
  `love` varchar(1024) DEFAULT NULL,
  `matchcity` varchar(11) NOT NULL DEFAULT '北京',
  `regtime` int(11) NOT NULL DEFAULT '0',
  `logintime` int(11) NOT NULL DEFAULT '0',
  `logouttime` int(11) NOT NULL DEFAULT '0',
  `modifytime` int(11) NOT NULL DEFAULT '0',
  `regstep` int(1) NOT NULL DEFAULT '0',
  `privatekey` varchar(32) DEFAULT '',
  PRIMARY KEY (`userid`),
  KEY `sex` (`sex`),
  KEY `email` (`email`),
  KEY `university` (`university`),
  KEY `birthday` (`birthday`),
  KEY `verify` (`verify`),
  KEY `locked` (`locked`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=59678 ;
